export { default as Navbar1 } from './Navbar1/Navbar';
export { default as Navbar2 } from './Navbar2/Navbar';
export { default as Navbar3 } from './Navbar3/Navbar';
export { default as Navbar4 } from './Navbar4/Navbar';
export { default as Infosection1 } from './InfoSection1/InfoSection' ;
export { default as Infosection2 } from './InfoSection2/InfoSection' ;
export { default as Infosection3 } from './InfoSection3/InfoSection' ;
export { default as Infosection4 } from './InfoSection4/InfoSection' ;
export { default as Brands } from './Brands/Brands';
export { default as Testimonial1 } from './Testimonial1/Testimonial';
export { default as Testimonial2 } from './Testimonial2/Testimonial';
export { default as Testimonial3 } from './Testimonial3/Testimonial';
export { default as Footer1 } from './footer1/Fotter';
export { default as Footer2 } from './footer2/Fotter';
export { default as Footer3 } from './footer3/Fotter';
export { default as Footer4 } from './footer4/Fotter';
export { default as Form1 } from './Form1/Form';
export { default as Form2 } from './Form2/Form';
export { default as Form3 } from './Form3/Form';
export { default as Form4 } from './Form4/Form';
export { default as Features1 } from './Features1/Feature';
export { default as Features2 } from './Features2/Feature';
export { default as Features3 } from './Features3/Feature';
export { default as Features4 } from './Features4/Feature';
export { default as Caresoul1 } from './Caresoul1/Carousel';
export { default as Caresoul2 } from './Caresoul2/Carousel';
export { default as Caresoul3 } from './Caresoul3/Properties';
export { default as Caresoul4 } from './Caresoul4/Carousel';
